// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Cargamos .env primero (defaults compartidos) y .env.local con override
// (secretos locales que no van a Git). Equivale al comportamiento de Next.js.
loadEnv({ path: ".env" });
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Preferimos DATABASE_URL (pooler) porque la conexión directa a Supabase
    // suele requerir IPv6 y falla desde redes IPv4. El pooler (puerto 6543)
    // es accesible vía IPv4 y sirve para migraciones simples de DDL.
    url: process.env["DATABASE_URL"] || process.env["DIRECT_URL"],
  },
});